### ISSUE TITLE
NonexistentSourceIdException when using output binding

### ISSUE THREAD

**Issue by cgillum** [Azure/Webjobs.Extensions.Kusto#40]
I'm trying to use the Kusto output binding to write data into a Kusto table. However, I'm getting the following exception when trying to use the output binding.

```
Kusto.Ingest.Exceptions.NonexistentSourceIdException: Failed to query ingestion status for source with ID:'7b2bf49d-d667-44ba-b46a-1057e8392a80'. A source with the provided ID does not exist.
  HResult=0x80131500
  Source=Kusto.Ingest
  StackTrace:
   at Kusto.Ingest.KustoIngestionResult.GetIngestionStatusBySourceId(Guid sourceId)
   at Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector`1.<IngestData>d__9.MoveNext()
   at Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector`1.<IngestRowsAsync>d__8.MoveNext()
   at Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector`1.<FlushAsync>d__7.MoveNext()
   at Microsoft.Azure.WebJobs.Host.Bindings.OutArrayValueProvider`1.<SetValueAsync>d__8.MoveNext() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Bindings\AsyncCollector\OutArrayValueProvider.cs:line 60

  This exception was originally thrown at this call stack:
    Kusto.Ingest.KustoIngestionResult.GetIngestionStatusBySourceId(System.Guid)
    Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector<T>.IngestData(string, Kusto.Ingest.KustoIngestionProperties, Kusto.Ingest.StreamSourceOptions)
    Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector<T>.IngestRowsAsync(System.Guid)
    Microsoft.Azure.WebJobs.Kusto.KustoAsyncCollector<T>.FlushAsync(System.Threading.CancellationToken)
    Microsoft.Azure.WebJobs.Host.Bindings.OutArrayValueProvider<TMessage>.SetValueAsync(object, System.Threading.CancellationToken) in OutArrayValueProvider.cs
```

I'm using the following package reference:

```xml
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Kusto" Version="1.0.7-Preview" />
```

Here is my function code:

```csharp
public record EmbeddingsRequest(string FilePath);

public record EmailEmbedding(string Subject, string Text, IReadOnlyList<double> Embeddings, DateTime Timestamp);

[FunctionName("EmailPrompt")]
public static IActionResult IngestEmail(
    [HttpTrigger(AuthorizationLevel.Function, "post")] EmbeddingsRequest req,
    [Embeddings("{FilePath}", InputType.FilePath, MaxChunkLength = 512)] EmbeddingCreateResponse embeddingsResponse,
    [Kusto("testing", TableName = "EmailEmbeddings", Connection = "KustoConnectionString")] out EmailEmbedding[] output,
    ILogger log)
{
    output = embeddingsResponse.Data.Select(
        d => new EmailEmbedding(
            Path.GetFileName(req.FilePath),
            "TODO: Text chunk",
            d.Embedding,
            DateTime.UtcNow)).ToArray();

    return new OkObjectResult(new
    {
        status = "success",
        count = output.Length,
    });
}
```

...and my connection string (copied from Kusto Explorer):

```
"KustoConnectionString": "Data Source=https://test-kusto-cluster.westus2.kusto.windows.net;Initial Catalog=NetDefaultDB;AAD Federated Security=True"
```

...which corresponds to an actual database in my Kusto cluster.

![image](https://github.com/Azure/Webjobs.Extensions.Kusto/assets/2704139/87251096-8a2f-436f-9fad-9d6df0e2f6ac)

The error message isn't really helpful, and searching for it online doesn't provide any information. Any ideas what might be causing my problem?

**Comment by ag-ramachandran** [comment]
Hello @cgillum, Thanks for reporting the issue. Will have a look as to why there is an issue. Could you in the meanwhile enable streaming on the table using the following command and give it a try again.

`.alter table EmailEmbeddings policy streamingingestion enable`

Happy to help you on this

**Comment by cgillum** [comment]
I tried running the following command:

```
.alter table EmailEmbeddings policy streamingingestion enable 
```

However, this resulted in an error:

```json
{
    "error": {
        "code": "BadRequest",
        "message": "Request is invalid and cannot be executed.",
        "@type": "Kusto.Common.Svc.Exceptions.AdminCommandInvalidStreamingIngestionOperationException",
        "@message": "Admin command cannot be executed as streaming ingestion is not enabled.",
        "@context": {
            "timestamp": "2023-06-21T07:06:08.8381158Z",
            "serviceAlias": "TEST-KUSTO-CLUSTER",
            "machineName": "KEngine000000",
            "processName": "Kusto.WinSvc.Svc",
            "processId": 4308,
            "threadId": 6348,
            "clientRequestId": "KE.RunCommand;844172e4-e9fe-4af9-be96-2a0693d9f9af",
            "activityId": "aa4c838d-92e3-4738-9b77-5659081664f8",
            "subActivityId": "c8a1aa30-169d-447b-90cd-f1fd1abb0617",
            "activityType": "DN.AdminCommand.TableStreamingIngestionPolicyAlterCommand",
            "parentActivityId": "2cb556c7-0c8a-4f37-b13c-c7dc943600fa",
            "activityStack": "(Activity stack: CRID=KE.RunCommand;844172e4-e9fe-4af9-be96-2a0693d9f9af ARID=aa4c838d-92e3-4738-9b77-5659081664f8 > DN.Admin.Client.ExecuteControlCommand/047dba49-c2c7-4639-a181-5617a057beff > P.WCF.Service.ExecuteControlCommand..IInterNodeCommunicationAdminContract/f55aed45-614f-466a-85ec-54a235e21794 > DN.FE.ExecuteControlCommand/2cb556c7-0c8a-4f37-b13c-c7dc943600fa > DN.AdminCommand.TableStreamingIngestionPolicyAlterCommand/c8a1aa30-169d-447b-90cd-f1fd1abb0617)"
        },
        "@permanent": true
    }
}
```

> Also, assuming here that you have App id / Key passed in the actual connection string as well.

I don't have App ID or Key in my connection string. I assumed that my user identity would be used since I'm running the function app locally with my own credentials. Could this be an auth issue? I tried adding `Authority Id` and `User ID` as shown below, but got the same exception.

```json
"KustoConnectionString": "Data Source=https://test-kusto-cluster.westus2.kusto.windows.net;Initial Catalog=NetDefaultDB;Fed=True;Authority Id=xxx;User ID=cgillum@xxx"
```

**Comment by ag-ramachandran** [comment]
Hello @cgillum 

Thanks for the reply. It could be an Auth issue

It could be an auth issue too, though the traces do not suggest that. Right now, we do not support User Id 

There are 2 options, either to use an App Id / App Key

`Data Source=https://test-kusto-cluster.westus2.kusto.windows.net;Database=testing;Fed=True;AppClientId=<APP-ID>;AppKey=<APP-KEY>;Authority Id=<TENANT>`

(or)

We can use Managed Identity if running from the portal (We'd have to create a managed identity with ingest privileges and then attached in the Annotation)



As for streaming, it can be enabled from the portal (this is only if the Auth is not working)

![image](https://github.com/Azure/Webjobs.Extensions.Kusto/assets/106139410/6c2546ff-ef66-4d76-9d35-22326b845e09)

and then `.alter table EmailEmbeddings policy streamingingestion enable `

**Comment by cgillum** [comment]
@ag-ramachandran enabling streaming worked! I was able to use the output binding successfully and query my data in Kusto Explorer.

Do the output bindings always require streaming ingestion to be enabled for the cluster and database?

**Comment by OlajideOgun** [comment]
@ag-ramachandran does the fix work ? I am facing the same issue. is the only work around to enable streaming?

**Comment by ag-ramachandran** [comment]
Hello @OlajideOgun, we did have regressions run against it. Will check it again. Quick q : Are you running this against Fabric/Synapse clusters

**Comment by skorunka** [comment]
Hello, experiencing the same issue. Do you guys plan to make this output binding work with streaming turned off? Thank you.

**Comment by ag-ramachandran** [comment]
@skorunka , Here was the consideration we had in this case. 

> Most of usage we see wrto ingest is with a few rows at best (large memory and time intensive operations are not great fitment for serverless scenarios)
> Queued ingest is not really well suited for this scenario due to latency (refer aggregation policies) and also "large number of small blobs" or the fragmentation scenario
> Streaming adds a little more CPU & was ideally suited for these scenarios

Changing from managed streaming to queued is not very hard to accomplish, if there are use cases that fit this case, it is something we could consider.

If you have a specific scenario that you'd like to use Queued with , happy to talk at ramacg @ <ms>.com

**Comment by skorunka** [comment]
Hi @ag-ramachandran, the only concert I have is cluster price. I got impression when the streaming is enabled the cluster costs more money, or am I wrong?

My use case is to actually ingest messages read from the IoT Hub right into Kusto table.

I was not able to make the IoT Hub Data connection on Kusto database working, so I decided to build the AzF that does that, and found this output binding that works quite nice.

Thank you.

**Comment by ag-ramachandran** [comment]
@skorunka , Streaming is part of the ADX BOM. No additional billing will entail if you enable it. It does take some additional cluster resources, but does not impact cost.

If you are in need of troubleshooting IoT hub connection (direct) , please let us know my email is above. Can get it directed at the right colleagues

**Comment by allojeswin** [comment]
@ag-ramachandran Since this thread is still open I have a similar error message. 

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.sync_snow_incidents ---> System.InvalidOperationException : Error while handling parameter _binder after function returned: ---> Kusto.Ingest.Exceptions.NonexistentSourceIdException : Failed to query ingestion status for source with ID:'xxxxx-xxxx-xxxx-xxxx'. A source with the provided ID does not exist.

    at Kusto.Ingest.KustoIngestionResult.GetIngestionStatusBySourceId(Guid sourceId).

After enabling streaming now my work is fine. I read online seeing posts about the additional cost that will be incurred due to this. I was unabe to find cost related data in azure document: https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming?WT.mc_id=Portal-Microsoft_Azure_Kusto&tabs=azure-portal%2Ccsharp . Can you please confirm if additional charges are applicable?

**Comment by ag-ramachandran** [comment]
> [@ag-ramachandran](https://github.com/ag-ramachandran) Since this thread is still open I have a similar error message.
> 
> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.sync_snow_incidents ---> System.InvalidOperationException : Error while handling parameter _binder after function returned: ---> Kusto.Ingest.Exceptions.NonexistentSourceIdException : Failed to query ingestion status for source with ID:'xxxxx-xxxx-xxxx-xxxx'. A source with the provided ID does not exist.
> 
> ```
> at Kusto.Ingest.KustoIngestionResult.GetIngestionStatusBySourceId(Guid sourceId).
> ```
> 
> After enabling streaming now my work is fine. I read online seeing posts about the additional cost that will be incurred due to this. I was unabe to find cost related data in azure document: https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming?WT.mc_id=Portal-Microsoft_Azure_Kusto&tabs=azure-portal%2Ccsharp . Can you please confirm if additional charges are applicable?

No additional billing will entail if you enable it. It does take some additional cluster resources,but does not impact cost.

IngestionType flag can be used to specify that we want to use Queued ingest. 

        /// <summary>
        /// The ingestion client to use. Supports managed,queued clients
        /// </summary>
        public string IngestionType { get; set; } = "managed";
